image: starefossen/ruby-node:latest

services:
  - postgres:latest

#db variables
variables:
  POSTGRES_USER: gitlab
  POSTGRES_PASSWORD: secret

before_script:
  - export RAILS_ENV=test
  # export scripts
  - mkdir cert
  # install dependencies
  - bundle install --path=/cache/bundle

rspec:
  stage: 'test'
  script:
    - apt-get update && apt-get install -y postgresql-client
    - bundle exec rake db:setup
    - bundle exec rake db:schema:load
    - bundle exec rspec --format doc
  artifacts:
    paths:
      - coverage/

lint:
  allow_failure: true
  stage: 'lint'
  script:
    - gem install rubocop
    - bundle exec rubocop

deploy:
  stage: 'deploy'
  script:
    - mkdir -p ~/.ssh
    - echo "${DEPLOY_KEY}" > ~/.ssh/id_rsa
    - chmod 400 ~/.ssh/id_rsa
    - export BRANCH_NAME=`echo $(echo $CI_COMMIT_REF_NAME | sed 's/\//_/g')`
    - export CD_ENV=`[[ "${BRANCH_NAME}" = "master" ]] && echo 'stage' || echo 'production'`
    - echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config
    - bundle exec cap $CD_ENV deploy
  only:
    # TODO: Add stage environment when available
    - production

stages:
  - test
  - lint
  - deploy
