version: '3'
services:
  db:
    image: postgres
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
  web:
    build: .
    ports:
      - '9000:9000'
    depends_on:
      - db
    env_file:
      - .env
